version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting up build environment..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Building for commit - $COMMIT_HASH"
      - RAW_MODEL_S3_URI="s3://custom-llm-model-directory/gemma3-12b/" 
      - DEPLOY_ARTIFACT_S3_URI="s3://sagemaker-gemma3-akhil-09oct/" 

  build:
    commands:
      - echo "Step 1: Creating staging directory"
      - mkdir staging
      
      - echo "Step 2: Syncing model files from S3. This may take a while..."
      - aws s3 sync $RAW_MODEL_S3_URI ./staging/
      
      - echo "Step 3: Copying inference code"
      - cp -r ./code ./staging/
      
      - echo "Step 4: Compressing artifact into model.tar.gz"
      - cd staging
      - tar -czvf ../model.tar.gz .
      - cd ..
      
      - echo "Step 5: Uploading final artifact to S3"
      - aws s3 cp model.tar.gz ${DEPLOY_ARTIFACT_S3_URI}model-${COMMIT_HASH}.tar.gz

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Final artifact is at ${DEPLOY_ARTIFACT_S3_URI}model-${COMMIT_HASH}.tar.gz"

artifacts:
  files:
    - model.tar.gz