name: Trigger AWS CodeBuild
on:
  push:
    branches: [ gemma3-12b ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Assumes you have set up an IAM Role for GitHub Actions (recommended)
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    - name: Start AWS CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: your-receipt-processor-build-project # The name of your project in AWS