name: Trigger AWS CodeBuild
on:
  push:
    branches: [ gemma3-12b ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Assumes you have set up an IAM Role for GitHub Actions (recommended)
        role-to-assume: arn:aws:iam::ACCOUNT-ID:role/your-github-actions-role
        aws-region: your-aws-region
    - name: Start AWS CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: your-receipt-processor-build-project # The name of your project in AWS